language: node_js

node_js: "8.11.1"

script: npm run-script build

deploy:

  provider: firebase

  skip_cleanup: true

  token:

    secure: $FIREBASE_TOKEN

  project: $FIREBASE_PROJECT

  on:

    branch: master
